### ISSUE TITLE
Grafana SQLite Plugin Problems

### ISSUE THREAD

**Issue by kevinvh001** [fr-ser/grafana-sqlite-datasource#44]
**Describe the bug**

**To Reproduce**

Hi Sergej,
I use Grafana on my MacBook Pro to visualise live data ported from Victron-Venus_Docker_Grafana. The data is ported to Grafana via http://localport:3000 and it works well.

I wish to visualise similar historical data stored on my hard drive. I am struggling because I have no programming capability or understanding of database structures.

I installed your SQLite plugin on my Venus-Docker_Grafana installation, but it will not accept the Path "/Users/kevinhiscox/Documents/sqlite3/GXData.sqlite3". It cannot find the database file which is definitely on my HD. I suspect there is a conflict caused by Grafana receiving the live data from http://localport:3000.

I them quit Venus-Docker_Grafana and installed a standalone Grafana installation with "brew install grafana". I started Grafana with Terminal and then opened Grafana in Safari using http://localport:3000. OK - new clean Grafana installation. I then tried installing your SQLite plugin, but when I clicked on DataSources, I got a message saying "The following plugins are disabled and not shown in the list below:
frser-sqlite-datasource Modified signature"

Can you help me please?

**Comment by fr-ser** [comment]
Hi. Please try to use the issue template. I am especially installed in the version of the plugin and Grafana as well as the installation method of the plugin (CLI vs manually copying).

But to already add some suggestions:
- You mentioned `docker` in your description. This is good because Docker gives a very nicely reproducible environment for Grafana. The path you provided (`/Users/kevinhiscox/Documents/sqlite3/GXData.sqlite3`) is however a local path. If you want to access folder from your local computer in a Docker container you need to use volumes ([see link](https://docs.docker.com/storage/volumes/))

- `The following plugins are disabled and not shown in the list below: frser-sqlite-datasource Modified signature`: This is a very interesting error message. I cannot help you a lot here without knowing more about your versions and installation method but to debug this error I would definitely need to see the logs of Grafana itself ([see link](https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs))
